# Generated by Django 3.2 on 2021-04-25 16:13

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.PositiveIntegerField()),
                ("name", models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("fruit", "fruit"), ("vegetable", "vegetable")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.UUIDField(db_index=True, unique=True)),
                ("person_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("has_died", models.BooleanField(default=False)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("picture", models.URLField()),
                ("birth_year", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "male"),
                            ("female", "female"),
                            ("nonbinary", "nonbinary"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                ("about", models.CharField(max_length=1000, null=True)),
                ("registered", models.DateTimeField()),
                ("greeting", models.CharField(default=False, max_length=200)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pandora.company",
                    ),
                ),
                (
                    "eye_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pandora.color"
                    ),
                ),
                ("favourite_foods", models.ManyToManyField(to="pandora.Food")),
                ("friends", models.ManyToManyField(to="pandora.Person")),
                ("tags", models.ManyToManyField(to="pandora.Tag")),
            ],
        ),
    ]
